export const CARDS = [
  { id: 1, response: 'Pele', category: 'Pessoa' },
  { id: 2, response: 'Rainha Elizabeth II', category: 'Pessoa' },
  { id: 3, response: 'Nelson Mandela', category: 'Pessoa' },
  { id: 4, response: 'Greta Thunberg', category: 'Pessoa' },
  { id: 5, response: 'Marie Curie', category: 'Pessoa' },
  { id: 6, response: 'Nikola Tesla', category: 'Pessoa' },
  { id: 7, response: 'Walt Disney', category: 'Pessoa' },
  { id: 8, response: 'Audrey Hepburn', category: 'Pessoa' },
  { id: 9, response: 'Charlie Chaplin', category: 'Pessoa' },
  { id: 10, response: 'Bruce Lee', category: 'Pessoa' },
  { id: 11, response: 'Oprah Winfrey', category: 'Pessoa' },
  { id: 12, response: 'Stephen Hawking', category: 'Pessoa' },
  { id: 13, response: 'Agatha Christie', category: 'Pessoa' },
  { id: 14, response: 'Santos Dumont', category: 'Pessoa' },
  { id: 15, response: 'Oscar Niemeyer', category: 'Pessoa' },
  { id: 16, response: 'Machado de Assis', category: 'Pessoa' },
  { id: 17, response: 'Carmen Miranda', category: 'Pessoa' },
  { id: 18, response: 'Zeus', category: 'Pessoa' },
  { id: 19, response: 'Batman', category: 'Pessoa' },
  { id: 20, response: 'Hermione Granger', category: 'Pessoa' },
  { id: 21, response: 'Hercule Poirot', category: 'Pessoa' },
  { id: 22, response: 'Vincent van Gogh', category: 'Pessoa' },
  { id: 23, response: 'Pablo Picasso', category: 'Pessoa' },
  { id: 24, response: 'Sigmund Freud', category: 'Pessoa' },
  { id: 25, response: 'Neil Armstrong', category: 'Pessoa' },
  { id: 26, response: 'Florence Nightingale', category: 'Pessoa' },
  { id: 27, response: 'Mahatma Gandhi', category: 'Pessoa' },
  { id: 28, response: 'Winston Churchill', category: 'Pessoa' },
  { id: 29, response: 'Marilyn Monroe', category: 'Pessoa' },
  { id: 30, response: 'Cristovao Colombo', category: 'Pessoa' },
  { id: 31, response: 'Torre de Pisa', category: 'Lugar' },
  { id: 32, response: 'Cristo Redentor', category: 'Lugar' },
  { id: 33, response: 'Grand Canyon', category: 'Lugar' },
  { id: 34, response: 'Muralha da China', category: 'Lugar' },
  { id: 35, response: 'Petra', category: 'Lugar' },
  { id: 36, response: 'Coliseu', category: 'Lugar' },
  { id: 37, response: 'Taj Mahal', category: 'Lugar' },
  { id: 38, response: 'Times Square', category: 'Lugar' },
  { id: 39, response: 'Hollywood', category: 'Lugar' },
  { id: 40, response: 'Canal do Panama', category: 'Lugar' },
  { id: 41, response: 'Santuario de Fatima', category: 'Lugar' },
  { id: 42, response: 'Stonehenge', category: 'Lugar' },
  { id: 43, response: 'Foz do Iguacu', category: 'Lugar' },
  { id: 44, response: 'Torres del Paine', category: 'Lugar' },
  { id: 45, response: 'Chichen Itza', category: 'Lugar' },
  { id: 46, response: 'Monte Everest', category: 'Lugar' },
  { id: 47, response: 'Antartida', category: 'Lugar' },
  { id: 48, response: 'Deserto do Saara', category: 'Lugar' },
  { id: 49, response: 'Piramides de Gize', category: 'Lugar' },
  { id: 50, response: 'Museu do Louvre', category: 'Lugar' },
  { id: 51, response: 'Torre Eiffel', category: 'Lugar' },
  { id: 52, response: 'Big Ben', category: 'Lugar' },
  { id: 53, response: 'Acropole de Atenas', category: 'Lugar' },
  { id: 54, response: 'Sagrada Familia', category: 'Lugar' },
  { id: 55, response: 'Galapagos', category: 'Lugar' },
  { id: 56, response: '1492', category: 'Ano' },
  { id: 57, response: '1500', category: 'Ano' },
  { id: 58, response: '1776', category: 'Ano' },
  { id: 59, response: '1789', category: 'Ano' },
  { id: 60, response: '1889', category: 'Ano' },
  { id: 61, response: '1914', category: 'Ano' },
  { id: 62, response: '1929', category: 'Ano' },
  { id: 63, response: '1939', category: 'Ano' },
  { id: 64, response: '1945', category: 'Ano' },
  { id: 65, response: '1960', category: 'Ano' },
  { id: 66, response: '1969', category: 'Ano' },
  { id: 67, response: '1974', category: 'Ano' },
  { id: 68, response: '1989', category: 'Ano' },
  { id: 69, response: '1997', category: 'Ano' },
  { id: 70, response: '2001', category: 'Ano' },
  { id: 71, response: '2008', category: 'Ano' },
  { id: 72, response: '2014', category: 'Ano' },
  { id: 73, response: '2016', category: 'Ano' },
  { id: 74, response: '2020', category: 'Ano' },
  { id: 75, response: '1822', category: 'Ano' },
  { id: 76, response: 'Telescopio', category: 'Coisa' },
  { id: 77, response: 'Helicoptero', category: 'Coisa' },
  { id: 78, response: 'DNA', category: 'Coisa' },
  { id: 79, response: 'Fotossintese', category: 'Coisa' },
  { id: 80, response: 'Chocolate', category: 'Coisa' },
  { id: 81, response: 'Globo terrestre', category: 'Coisa' },
  { id: 82, response: 'Ampulheta', category: 'Coisa' },
  { id: 83, response: 'Barometro', category: 'Coisa' },
  { id: 84, response: 'Roda', category: 'Coisa' },
  { id: 85, response: 'Fogo', category: 'Coisa' },
  { id: 86, response: 'Espelho', category: 'Coisa' },
  { id: 87, response: 'GPS', category: 'Coisa' },
  { id: 88, response: 'Drone', category: 'Coisa' },
  { id: 89, response: 'Sombra', category: 'Coisa' },
  { id: 90, response: 'Eco', category: 'Coisa' },
  { id: 91, response: 'Esperanca', category: 'Coisa' },
  { id: 92, response: 'Gravidade', category: 'Coisa' },
  { id: 93, response: 'Laser', category: 'Coisa' },
  { id: 94, response: 'Parafuso', category: 'Coisa' },
  { id: 95, response: 'Microfone', category: 'Coisa' },
  { id: 96, response: 'Paraquedas', category: 'Coisa' },
  { id: 97, response: 'Ima', category: 'Coisa' },
  { id: 98, response: 'Termometro', category: 'Coisa' },
  { id: 99, response: 'Paralelogramo', category: 'Coisa' },
  { id: 100, response: 'QR Code', category: 'Coisa' },
]
