export const CARDS = [
  { id: 1, response: 'Ada Lovelace', category: 'Pessoa' },
  { id: 2, response: 'Ayrton Senna', category: 'Pessoa' },
  { id: 3, response: 'Sherlock Holmes', category: 'Pessoa' },
  { id: 4, response: 'Frida Kahlo', category: 'Pessoa' },
  { id: 5, response: 'Bombeiro', category: 'Pessoa' },
  { id: 6, response: 'Darth Vader', category: 'Pessoa' },
  { id: 7, response: 'Machu Picchu', category: 'Lugar' },
  { id: 8, response: 'Toquio', category: 'Lugar' },
  { id: 9, response: 'Amazonia', category: 'Lugar' },
  { id: 10, response: 'Biblioteca', category: 'Lugar' },
  { id: 11, response: 'Maracana', category: 'Lugar' },
  { id: 12, response: '1969', category: 'Ano' },
  { id: 13, response: '1989', category: 'Ano' },
  { id: 14, response: '2001', category: 'Ano' },
  { id: 15, response: '1822', category: 'Ano' },
  { id: 16, response: 'Bussola', category: 'Coisa' },
  { id: 17, response: 'Violao', category: 'Coisa' },
  { id: 18, response: 'Polvo', category: 'Coisa' },
  { id: 19, response: 'Saudade', category: 'Coisa' },
  { id: 20, response: 'Internet', category: 'Coisa' },
  { id: 21, response: 'Pelé', category: 'Pessoa' },
  { id: 22, response: 'Marie Curie', category: 'Pessoa' },
  { id: 23, response: 'Nelson Mandela', category: 'Pessoa' },
  { id: 24, response: 'William Shakespeare', category: 'Pessoa' },
  { id: 25, response: 'Amelia Earhart', category: 'Pessoa' },
  { id: 26, response: 'Cristo Redentor', category: 'Lugar' },
  { id: 27, response: 'Paris', category: 'Lugar' },
  { id: 28, response: 'Grande Barreira de Coral', category: 'Lugar' },
  { id: 29, response: 'Ilha de Páscoa', category: 'Lugar' },
  { id: 30, response: 'Nova York', category: 'Lugar' },
  { id: 31, response: '1492', category: 'Ano' },
  { id: 32, response: '1914', category: 'Ano' },
  { id: 33, response: '1945', category: 'Ano' },
  { id: 34, response: '1963', category: 'Ano' },
  { id: 35, response: '2000', category: 'Ano' },
  { id: 36, response: 'Relógio', category: 'Coisa' },
  { id: 37, response: 'Câmera', category: 'Coisa' },
  { id: 38, response: 'Bicicleta', category: 'Coisa' },
  { id: 39, response: 'Computador', category: 'Coisa' },
  { id: 40, response: 'Café', category: 'Coisa' },
]