export const CARDS = [
  { id: 1, response: 'Ada Lovelace', category: 'Pessoa' },
  { id: 2, response: 'Ayrton Senna', category: 'Pessoa' },
  { id: 3, response: 'Sherlock Holmes', category: 'Pessoa' },
  { id: 4, response: 'Frida Kahlo', category: 'Pessoa' },
  { id: 5, response: 'Bombeiro', category: 'Pessoa' },
  { id: 6, response: 'Darth Vader', category: 'Pessoa' },
  { id: 7, response: 'Machu Picchu', category: 'Lugar' },
  { id: 8, response: 'Toquio', category: 'Lugar' },
  { id: 9, response: 'Amazonia', category: 'Lugar' },
  { id: 10, response: 'Biblioteca', category: 'Lugar' },
  { id: 11, response: 'Maracana', category: 'Lugar' },
  { id: 12, response: '1969', category: 'Ano' },
  { id: 13, response: '1989', category: 'Ano' },
  { id: 14, response: '2001', category: 'Ano' },
  { id: 15, response: '1822', category: 'Ano' },
  { id: 16, response: 'Bussola', category: 'Coisa' },
  { id: 17, response: 'Violao', category: 'Coisa' },
  { id: 18, response: 'Polvo', category: 'Coisa' },
  { id: 19, response: 'Saudade', category: 'Coisa' },
  { id: 20, response: 'Internet', category: 'Coisa' },
  { id: 21, response: 'Pelé', category: 'Pessoa' },
  { id: 22, response: 'Marie Curie', category: 'Pessoa' },
  { id: 23, response: 'Nelson Mandela', category: 'Pessoa' },
  { id: 24, response: 'William Shakespeare', category: 'Pessoa' },
  { id: 25, response: 'Amelia Earhart', category: 'Pessoa' },
]