const CARD_TIPS: Record<number, string[]> = {
  1: [
    'Meu trabalho ficou adormecido por muitas decadas.',
    'Vivi na Inglaterra no seculo XIX.',
    'Nasci em uma familia ligada a poesia romantica.',
    'Escrevi sobre uma maquina que ainda nem existia de fato.',
    'Minha contribuicao ficou famosa muito depois da minha morte.',
    'Trabalhei com tabelas, simbolos e logica.',
    'Sou lembrada em debates sobre mulheres na tecnologia.',
    'Meu sobrenome de casada nao era o mesmo do meu pai famoso.',
    'Trabalhei com um matematico inventor de uma maquina analitica.',
    'Anotei um metodo para calcular numeros de Bernoulli.',
    'Esse metodo e considerado por muitos um programa pioneiro.',
    'Meu texto ia alem de simples contas numericas.',
    'Vi potencial de manipular tambem musica e linguagem por simbolos.',
    'Fui chamada de encantadora dos numeros por um colega.',
    'Meu primeiro nome aparece em uma linguagem de programacao.',
    'Sou frequentemente citada como pioneira da computacao.',
    'Meu pai foi Lord Byron.',
    'Meu parceiro intelectual foi Charles Babbage.',
    'Meu trabalho foi feito para a Engine Analitica.',
    'Meu nome completo une Ada a um sobrenome aristocratico ingles.',
  ],
  2: [
    'Virei simbolo de excelencia no esporte do meu pais.',
    'Competi em uma modalidade de velocidade extrema.',
    'Fiquei famoso por concentracao intensa antes das disputas.',
    'Usei capacete com cores muito reconheciveis.',
    'Tive grande rivalidade com um frances multicampeao.',
    'Meu talento apareceu cedo em categorias de base.',
    'Corri por equipes tradicionais europeias.',
    'Meu estilo em pista misturava agressividade e precisao.',
    'Ganhei provas em condicoes de chuva consideradas impossiveis.',
    'Conquistei tres titulos mundiais.',
    'Meu nome batiza avenidas, escolas e institutos.',
    'Uma vitoria marcante veio no Japao no fim dos anos 80.',
    'No Brasil, domingos de corrida ficaram associados a mim.',
    'Minha bandeira nacional aparecia no cockpit apos vitorias.',
    'Muitos me chamavam de idolo nacional.',
    'Minha carreira foi interrompida tragicamente em Imola.',
    'Aconteceu durante um Grande Premio em 1994.',
    'Sou lembrado como lenda da Formula 1.',
    'Meu primeiro nome e Ayrton.',
    'Meu nome completo une Ayrton a um sobrenome de quatro letras.',
  ],
  3: [
    'Sou uma mente ficticia extremamente analitica.',
    'Resolvo misterios com observacao minuciosa.',
    'Atuo em historias ambientadas na Inglaterra vitoriana.',
    'Tenho um companheiro medico que narra varios casos.',
    'Meu criador era um escritor e medico escoces.',
    'Costumo perceber detalhes que outros ignoram.',
    'Tenho um inimigo intelectual de grande reputacao criminosa.',
    'Ja fui retratado em livros, filmes e series.',
    'Meu endereco literario ficou famoso mundialmente.',
    'Uso raciocinio dedutivo como marca principal.',
    'Sou associado a lupa e cachimbo em representacoes classicas.',
    'Tenho perfil frio, logico e pouco paciente.',
    'Meu parceiro de investigacoes se chama Watson.',
    'Meu arqui-inimigo e Moriarty.',
    'Moro na Baker Street, numero 221B.',
    'Fui criado por Arthur Conan Doyle.',
    'Sou um detetive consultor.',
    'Meu nome proprio e o mesmo de um famoso ator americano.',
    'Meu sobrenome e Holmes.',
    'Meu nome completo junta um prenome classico a Holmes.',
  ],
  4: [
    'Transformei dor pessoal em arte marcante.',
    'Minha obra mistura realidade, simbolismo e autobiografia.',
    'Nasci e vivi no Mexico.',
    'Meu rosto se tornou icone cultural global.',
    'Pintei muitos autorretratos ao longo da vida.',
    'Uma limitacao fisica influenciou meu processo criativo.',
    'Cores fortes e elementos da cultura popular mexicana aparecem no meu trabalho.',
    'Fui ligada a movimentos politicos de esquerda.',
    'Meu relacionamento com outro pintor famoso foi intenso e turbulento.',
    'Minha casa azul virou museu.',
    'Usei roupas tradicionais como afirmacao identitaria.',
    'Minha sobrancelha marcante virou assinatura visual.',
    'Tive um acidente de onibus na juventude.',
    'Meu companheiro foi Diego Rivera.',
    'Minha obra ganhou enorme reconhecimento apos minha morte.',
    'Sou referencia em debates sobre feminismo e representacao.',
    'Meu primeiro nome tem cinco letras.',
    'Meu sobrenome comeca com K.',
    'Sou Frida.',
    'Meu nome completo junta Frida a um sobrenome curto de origem germanica.',
  ],
  5: [
    'Trabalho quando muitos estao correndo para longe.',
    'Meu dia a dia exige preparo fisico e emocional.',
    'Atuo em equipes coordenadas por radios e protocolos.',
    'Lido com emergencias urbanas e residenciais.',
    'Uso equipamentos de protecao pesados.',
    'Minha rotina inclui treinamentos constantes.',
    'Entro em locais com calor extremo e baixa visibilidade.',
    'Tambem ajudo em enchentes, resgates e acidentes.',
    'Meu veiculo costuma chamar atencao nas ruas.',
    'Mangueiras e escadas estao entre minhas ferramentas.',
    'Capacete e roupa antichamas fazem parte do uniforme.',
    'Posso atuar em salvamento em altura.',
    'Muitos me chamam em situacoes de curto-circuito e fumaca.',
    'Atendo ligacoes de emergencia 24 horas.',
    'Minha missao principal e proteger vidas.',
    'Sou associado a sirenes e quartel.',
    'Combato incendios.',
    'Faco parte do corpo de salvamento.',
    'Minha profissao comeca com B.',
    'Minha profissao e a primeira lembrada quando se fala em apagar fogo.',
  ],
  6: [
    'Sou um dos maiores viloes da cultura pop.',
    'Minha presenca e ligada a poder e medo.',
    'Uso vestimenta escura quase o tempo todo.',
    'Tenho ligacao familiar central para a saga em que apareco.',
    'Fui treinado em uma ordem de guerreiros misticos.',
    'Troquei meu antigo caminho por um lado sombrio.',
    'Minha voz grave e inconfundivel em varias versoes.',
    'Carrego uma arma de energia em duelos.',
    'Meu visual inclui mascara e respiracao mecanica.',
    'Sirvo a um lider autoritario de um imperio galactico.',
    'Meu passado inclui talento excepcional com a Forca.',
    'Pilotei naves e cacas em batalhas espaciais.',
    'Minha historia envolve queda, culpa e redencao.',
    'Tenho relacao direta com Luke e Leia.',
    'Meu nome de nascimento era Anakin.',
    'Sou do universo de Star Wars.',
    'Meu sobrenome e Vader.',
    'Meu primeiro nome comeca com D.',
    'Meu nome completo combina um titulo curto com Vader.',
    'Sou o pai de Luke Skywalker.',
  ],
  7: [
    'Fui construida em altitude elevada.',
    'Minha origem envolve um grande imperio pre-colombiano.',
    'Fico em uma regiao montanhosa da America do Sul.',
    'Fiquei escondida para boa parte do mundo por seculos.',
    'Minhas estruturas de pedra impressionam pela engenharia.',
    'Nao fui erguida com argamassa comum entre blocos.',
    'Sou cercada por picos e neblina frequente.',
    'Muitos visitantes chegam de trem e trilhas.',
    'Meu local e associado a lama e alpacas da regiao andina.',
    'Sou considerada patrimonio mundial.',
    'Meu nome em quechua tem relacao com montanha antiga.',
    'Fico perto de Cusco.',
    'Estou no Peru.',
    'Sou uma das paisagens mais fotografadas do continente.',
    'Meu acesso classico inclui a Trilha Inca.',
    'Fui revelada ao publico internacional por Hiram Bingham.',
    'Sou uma antiga cidade inca.',
    'Meu nome comeca com M.',
    'Meu nome termina com Picchu.',
    'Meu nome completo combina duas palavras de origem quechua.',
  ],
  8: [
    'Sou uma metropole que mistura tradicao e tecnologia.',
    'Tenho bairros com ritmos e estilos muito diferentes.',
    'Minha rede de transporte e conhecida pela eficiencia.',
    'Fico em um arquipelago no leste da Asia.',
    'Sou enorme em populacao e influencia economica.',
    'Neons e telas gigantes marcam algumas das minhas areas.',
    'Tambem tenho templos antigos e jardins serenos.',
    'Sediar megaeventos internacionais faz parte da minha historia.',
    'Minha culinaria e reverenciada no mundo inteiro.',
    'Tenho cruzamentos famosos com fluxo intenso de pedestres.',
    'Sou referencia em eletronicos, games e cultura pop.',
    'Na primavera, cerejeiras atraem multidoes.',
    'Meu pais usa iene como moeda.',
    'Fui sede dos Jogos Olimpicos em 1964 e novamente decadas depois.',
    'Meu antigo nome oficial foi Edo.',
    'Sou a capital do Japao.',
    'Meu nome em portugues leva acento na vogal final.',
    'Comeco com T.',
    'Termino com quio.',
    'Sou a capital japonesa conhecida por tecnologia e tradicao.',
  ],
  9: [
    'Sou vastidao natural de escala continental.',
    'Abrigo biodiversidade considerada unica no planeta.',
    'Meus rios formam uma rede gigantesca.',
    'Influencio ciclos de chuva em varias regioes.',
    'Sou tema central em discussoes ambientais globais.',
    'Muitos povos originarios vivem em meu territorio.',
    'Minha vegetacao e predominantemente tropical.',
    'Enfrento pressao por desmatamento e queimadas.',
    'Sou dividida entre varios paises sul-americanos.',
    'Meu maior rio compartilha meu nome em muitas linguas.',
    'Sou chamada por alguns de pulmão do mundo, embora a expressao seja debatida.',
    'Minha fauna inclui oncas, araras e botos.',
    'No Brasil, ocupo grande parte da regiao Norte.',
    'Tenho importancia climatica planetaria.',
    'Sou uma floresta tropical.',
    'Meu nome comeca com A.',
    'Tambem nomeio um estado brasileiro.',
    'Meu nome termina com nia.',
    'Sou a maior floresta tropical do planeta.',
    'Meu nome identifica uma regiao natural sul-americana gigantesca.',
  ],
  10: [
    'Sou um lugar de silencio relativo e concentracao.',
    'Minha funcao principal e guardar conhecimento organizado.',
    'Posso existir em escolas, bairros, universidades e meios digitais.',
    'Sou frequentada para estudo, pesquisa e leitura.',
    'Costumo ter regras sobre volume de voz.',
    'Em mim, obras ficam catalogadas por sistemas de classificacao.',
    'Emprestimos costumam ter prazo de devolucao.',
    'Ha profissionais especializados em curadoria de acervo.',
    'Posso ter setores infantil, tecnico e de referencia.',
    'Muitas pessoas me visitam em epoca de provas.',
    'Prateleiras e estantes sao elementos tipicos do meu espaco.',
    'Tambem posso oferecer acesso a rede mundial e bases academicas.',
    'Cartoes de usuario ajudam no controle de retirada.',
    'Autores de varias epocas convivem no meu acervo.',
    'Sou associada a livros, periodicos e manuscritos.',
    'Meu nome comeca com B.',
    'Sou um estabelecimento cultural comum.',
    'Sem mim, pesquisar fica muito mais dificil.',
    'Meu nome termina com teca.',
    'Sou o lugar classico para emprestimo de livros.',
  ],
  11: [
    'Sou um palco esportivo de enorme capacidade.',
    'Estou ligado a paixao coletiva e grandes classicos.',
    'Minha localizacao fica em uma cidade famosa por praias e morros.',
    'Ja recebi finais e eventos historicos do futebol.',
    'Minha atmosfera e conhecida por cantos de torcida.',
    'Passei por reformas para torneios internacionais recentes.',
    'Meu apelido remete a grandiosidade.',
    'Sou administrado como complexo multiuso em diferentes periodos.',
    'Fico na zona norte da minha cidade.',
    'Partidas da selecao brasileira ja aconteceram em mim.',
    'Recebi uma final de Copa do Mundo no seculo XX.',
    'Tambem sediou final de mundial de selecoes no seculo XXI.',
    'Meu bairro tem o mesmo nome que eu.',
    'Estou no Rio de Janeiro.',
    'Sou um estadio brasileiro muito famoso.',
    'Meu nome oficial homenageia um jornalista.',
    'O nome oficial inclui Mario Filho.',
    'Meu apelido comeca com Mara.',
    'Meu apelido termina com cana.',
    'Sou o estadio carioca mais famoso do pais.',
  ],
  12: [
    'Este ano marcou transformacoes simbolicas na corrida espacial.',
    'Foi uma epoca de mudancas culturais fortes no mundo.',
    'Aconteceu um grande festival de musica nos EUA.',
    'Uma franquia de ficcao cientifica estreou no cinema no fim do ano.',
    'Protestos e movimentos sociais cresceram em varios paises.',
    'A Guerra Fria influenciava quase toda decisao geopolitica.',
    'No Brasil, o periodo era de ditadura militar.',
    'Um ato institucional muito duro havia sido decretado pouco antes.',
    'Tecnologia de transmissao levou eventos para audiencias massivas.',
    'A disputa entre duas superpotencias estava no auge.',
    'Um modulo pousou em solo fora da Terra.',
    'Uma frase sobre um pequeno passo virou simbolo historico.',
    'Milhoes assistiram a chegada pela TV.',
    'A missao era da NASA.',
    'A nave envolvida foi a Apollo 11.',
    'Neil Armstrong participou desse feito.',
    'Foi o ano da primeira ida humana a Lua.',
    'Fica no fim da decada de 60.',
    'Vem imediatamente antes de 1970.',
    'E o ultimo ano da decada de 60.',
  ],
  13: [
    'Este ano alterou mapas politicos na Europa.',
    'Mudancas democraticas aceleraram no leste europeu.',
    'Foi um periodo de fim de blocos ideologicos rigidos.',
    'Imagens de multidoes derrubando barreiras ficaram famosas.',
    'No Brasil, aconteceu a primeira eleicao presidencial direta apos regime militar.',
    'A cultura pop viveu transicoes importantes no final da decada.',
    'A Uniao Sovietica ainda existia, mas enfraquecida.',
    'Discursos por liberdade ganharam forca em varios paises.',
    'Reformas economicas e politicas se intensificaram.',
    'A Guerra Fria se aproximava do encerramento.',
    'Em Pequim, manifestacoes estudantis terminaram com repressao.',
    'Na Alemanha, uma divisao fisica perdeu sentido.',
    'A queda de um muro simbolizou nova era europeia.',
    'Esse evento ocorreu em Berlim.',
    'No Brasil, Fernando Collor foi eleito.',
    'Fica no fim dos anos 80.',
    'E o ultimo ano antes de 1990.',
    'Termina com 89.',
    'Comeca com 19.',
    'E o ultimo ano da decada de 80.',
  ],
  14: [
    'Este ano comecou com grande tensao internacional.',
    'A tecnologia digital ja influenciava fortemente a vida urbana.',
    'Foi um periodo de mudancas em seguranca global.',
    'Mercados financeiros sentiram forte instabilidade no segundo semestre.',
    'Debates sobre vigilancia e fronteiras cresceram muito.',
    'No Brasil, energia eletrica virou tema cotidiano por causa de racionamento.',
    'No esporte, um brasileiro virou penta campeao mundial de Formula 1 na virada do ano.',
    'Na musica, o inicio dos anos 2000 consolidou novas tendencias pop.',
    'A rede mundial comercial seguia em expansao acelerada.',
    'Ataques coordenados chocaram os Estados Unidos.',
    'As imagens envolveram avioes e arranha-ceus.',
    'O Pentagono tambem foi atingido.',
    'A data desses ataques foi 11 de setembro.',
    'A chamada guerra ao terror ganhou impulso depois disso.',
    'Foi o primeiro ano do seculo XXI.',
    'Tambem foi o primeiro ano do terceiro milenio.',
    'Vem logo depois de 2000.',
    'Fica antes de 2002.',
    'Termina com 01.',
    'E o primeiro ano dos anos 2000.',
  ],
  15: [
    'Este ano e central para a historia politica do Brasil.',
    'Aconteceu no inicio do seculo XIX.',
    'Foi periodo de ruptura com uma metropole europeia.',
    'Movimentos locais ja defendiam autonomia havia algum tempo.',
    'A corte portuguesa havia se transferido para a America anos antes.',
    'Conflitos de interesse entre colonia e reino aumentaram.',
    'Um principe regente teve papel decisivo.',
    'Uma declaracao celebrou separacao politica.',
    'O episodio ficou associado a uma margem de rio paulista.',
    'A frase atribuida ao momento ficou muito conhecida nas escolas.',
    'Depois desse marco, iniciou-se organizacao do novo imperio.',
    'A data celebrada no calendario nacional e em setembro.',
    'O dia e sete de setembro.',
    'A independencia brasileira foi proclamada.',
    'O protagonista foi Dom Pedro I.',
    'Fica na decada de 1820.',
    'O ano termina com 22.',
    'Comeca com 18.',
    'Vem apos 1821.',
    'E o ano da independencia do Brasil.',
  ],
  16: [
    'Sou pequena, mas mudo direcoes em viagens.',
    'Funciono melhor quando posso me alinhar com um campo natural.',
    'Fui essencial para navegadores por seculos.',
    'Tenho relacao historica com exploracoes maritimas.',
    'Posso aparecer em versoes analogicas e digitais.',
    'Minha parte movel aponta para uma referencia fixa do planeta.',
    'Ajudo em trilhas, mapas e orientacao terrestre.',
    'Sou comum em kits de sobrevivencia.',
    'Posso ser integrada a relogios e celulares.',
    'Sem mim, orientar-se sem pontos visuais fica dificil.',
    'Meu funcionamento tradicional usa agulha magnetizada.',
    'Cardeais como norte e sul sao fundamentais para mim.',
    'No painel de carros, ha versoes eletronicas inspiradas em mim.',
    'Sou muito usada em atividades de escotismo.',
    'Meu corpo pode ser circular com rosa dos ventos.',
    'Meu nome comeca com B.',
    'Tenho dois ss no meio.',
    'Sou instrumento de orientacao.',
    'Meu nome termina com ola.',
    'Sou o instrumento classico que aponta o norte magnetico.',
  ],
  17: [
    'Produzo som por vibracao de cordas.',
    'Sou popular em rodas informais e palcos.',
    'Posso acompanhar voz em varios estilos.',
    'Existem modelos acusticos e eletricos aparentados comigo.',
    'Tenho corpo oco em uma versao muito comum.',
    'Mao esquerda e direita costumam ter funcoes diferentes ao tocar.',
    'Uso trastes para definir notas em grande parte dos modelos.',
    'Aprender acordes basicos e um passo inicial para iniciantes.',
    'Estou presente em samba, rock, pop, sertanejo e bossa.',
    'Posso ser tocado com dedos ou palheta.',
    'Minha afinacao padrao de seis cordas e bastante conhecida.',
    'No Brasil, sou presenca frequente em praias e encontros.',
    'Tenho parentes proximos como cavaquinho e viola.',
    'Meu braco se conecta a um corpo em formato caracteristico.',
    'Fabricantes usam madeiras variadas para timbre diferente.',
    'Meu nome comeca com V.',
    'Sou muito ensinado em aulas de musica.',
    'Nao sou um piano nem um violino.',
    'Tenho seis cordas na versao mais comum.',
    'Sou o instrumento de seis cordas mais comum nas rodas de musica.',
  ],
  18: [
    'Sou um animal marinho sem esqueleto interno rigido.',
    'Tenho inteligencia acima da media entre invertebrados.',
    'Consigo resolver problemas simples e abrir recipientes.',
    'Meu corpo e extremamente flexivel.',
    'Posso mudar de cor para camuflagem.',
    'Expulso tinta para confundir predadores.',
    'Vivo em oceanos de varias temperaturas.',
    'Tenho olhos muito desenvolvidos.',
    'Meu deslocamento pode ocorrer por jato de agua.',
    'Nao tenho concha externa como alguns parentes.',
    'Meus membros possuem ventosas.',
    'Cada membro consegue manipular objetos com precisao.',
    'Sou estudado em neurociencia por meu sistema nervoso complexo.',
    'Em culinarias costeiras, apareco em diferentes pratos.',
    'Meu nome em portugues e curto e termina com o.',
    'Tenho oito bracos.',
    'Pertenco ao grupo dos cefalopodes.',
    'Nao sou lula, embora seja parente.',
    'Meu nome comeca com P.',
    'Sou o cefalopode famoso por oito bracos com ventosas.',
  ],
  19: [
    'Nao sou objeto fisico, mas posso pesar muito.',
    'Apareco com forca quando existe distancia.',
    'Tenho relacao com memoria afetiva.',
    'Posso nascer de pessoas, lugares, fases ou cheiros.',
    'Sou tema frequente de musica e poesia.',
    'Nem sempre estou ligada a tristeza pura.',
    'Tambem posso trazer conforto e identidade.',
    'Sou dificil de traduzir literalmente para muitos idiomas.',
    'No Brasil, sou entendida de imediato em conversas.',
    'Estou presente quando algo importante fica para tras.',
    'Posso surgir em quem migra de cidade ou pais.',
    'Muitas cartas e cancoes antigas falam de mim.',
    'Sou um sentimento complexo.',
    'Misturo ausencia e carinho na mesma experiencia.',
    'Costumo crescer em datas comemorativas.',
    'Meu nome comeca com S.',
    'Tenho ditongo nasal na ultima silaba.',
    'Sou palavra muito associada ao portugues.',
    'Meu nome termina com dade.',
    'Sou o sentimento de falta carregado de afeto.',
  ],
  20: [
    'Conecto pessoas e informacoes em escala global.',
    'Nao sou um unico aparelho, mas uma rede gigantesca.',
    'Meu crescimento acelerou no fim do seculo XX.',
    'Permito comunicacao quase instantanea entre continentes.',
    'Sou base para emails, videos, mapas e mensagens.',
    'Tambem viabilizo compras, aulas e trabalho remoto.',
    'Tenho riscos ligados a privacidade e desinformacao.',
    'Meu funcionamento envolve protocolos de dados.',
    'Servidores, roteadores e cabos fazem parte da minha estrutura.',
    'Posso chegar por fibra, radio, satelite ou rede movel.',
    'Navegadores sao portas comuns para me acessar.',
    'Buscadores ajudam usuarios a encontrar conteudo dentro de mim.',
    'Redes sociais dependem fortemente da minha existencia.',
    'Sem mim, muitos servicos digitais param.',
    'No cotidiano, as pessoas dizem que estao sem sinal quando nao me alcancam.',
    'Meu nome comeca com I.',
    'A web e apenas uma parte de mim.',
    'Nao sou sinonimo exato de Wi-Fi.',
    'Tenho alcance mundial.',
    'Sou a rede digital global que conecta o mundo.',
  ],
  21: [
    'Profissionalizou-se ainda jovem na década de 1950.',
    'Conhecido por dribles, infiltrações e finalizações de rara precisão.',
    'Fez a maior parte da carreira em um clube tradicional do litoral paulista.',
    'Alcançou status de ídolo nacional por desempenhos consistentes em competições locais e internacionais.',
    'Destacou-se por combinar técnica, velocidade e poder de finalização.',
    'Tornou-se referência em gols e jogadas plásticas que entraram para a história do esporte.',
    'Participou de conquistas de sua seleção em torneios mundiais.',
    'Também atuou em uma liga estrangeira no fim da carreira, ajudando a popularizar o esporte lá.',
    'Recebeu homenagens e títulos honorários durante e após sua carreira ativa.',
    'É frequentemente citado em debates sobre o melhor jogador do século XX.',
    'Sua imagem é associada a grandes festas e celebrações do futebol no país.',
    'Era atacante com grande mobilidade e faro de gol.',
    'Multiplicou gols em amistosos, torneios internacionais e campeonatos nacionais.',
    'Vários documentários e filmes recontam suas partidas históricas.',
    'Foi apelidado por fãs e imprensa com um título curto que remete a nobreza no campo.',
    'Sua trajetória começou em poucos clubes, mas com impacto enorme em cada um deles.',
    'Considerado por muitos uma lenda do futebol nacional e mundial.',
    'Sua carreira juvenil chamou atenção de olheiros e diretoria profissional cedo.',
    'É lembrado tanto por gols fáceis quanto por jogadas acrobáticas.',
    'Seu legado inclui estatísticas de gols que poucos alcançaram.'
  ],
  22: [
    'Cientista que trabalhou em materiais radioativos no fim do século XIX e início do XX.',
    'Nasceu em território do Leste Europeu e estabeleceu carreira em Paris.',
    'Publicou descobertas sobre elementos químicos então recém-identificados.',
    'Colaborou intensamente com um parceiro científico próximo durante parte da vida.',
    'Recebeu a mais alta distinção científica em duas ocasiões por contribuições distintas.',
    'Seus estudos deram origem a aplicações médicas da radioatividade anos depois.',
    'Fundou ou ajudou a criar institutos que promoveram pesquisa científica contínua.',
    'Sofreu exposição a agentes que afetaram sua saúde, em uma época sem proteção adequada.',
    'Uma das descobertas recebeu nome em referência à sua terra natal.',
    'Enfrentou barreiras de gênero em sua carreira acadêmica e profissional.',
    'É lembrada como pioneira feminina na ciência moderna.',
    'Alguns de seus descendentes também seguiram carreira científica.',
    'Trabalhou em uma universidade parisiense de grande prestígio.',
    'Seus arquivos e equipamentos históricos ainda geram interesse de pesquisadores.',
    'Recebeu prêmios reconhecidos internacionalmente por trabalho em áreas distintas.',
    'Publicações suas estabeleceram bases para pesquisas futuras em física e química.',
    'Seu legado ajudou a consolidar métodos experimentais em radiologia.',
    'Documentários e biografias enfatizam sua persistência no meio científico.',
    'Sua trajetória é citada em discussões sobre mulheres nas ciências exatas.',
    'É lembrada por ter ampliado o entendimento sobre elementos e radioatividade.'
  ],
  23: [
    'Líder que lutou contra um sistema institucionalizado de segregação racial.',
    'Passou longos anos preso por atividades políticas consideradas subversivas pelo regime.',
    'Cumpriu parte de sua pena em uma prisão insular conhecida internacionalmente.',
    'A libertação desse líder foi marco que antecedeu profundas mudanças políticas no país.',
    'Posteriormente foi eleito para a mais alta posição executiva do seu país em voto democrático multirracial.',
    'Recebeu um prêmio internacional importante por esforços em reconciliação e paz.',
    'Promoveu políticas de reconciliação após anos de conflito racial institucionalizado.',
    'Começou a carreira profissional como advogado antes de se dedicar à política.',
    'Seu país está localizado na ponta sul do continente africano.',
    'É símbolo mundial de resistência, perdão e liderança moral.',
    'Sua figura inspirou movimentos por igualdade e justiça ao redor do mundo.',
    'Muitos protestos internacionais pediam sua libertação enquanto permaneceu preso.',
    'Seu estilo de liderança privilegiou negociações e soluções pacíficas.',
    'A vida desse líder é tema frequente em aulas de história contemporânea.',
    'A imagem pública associou-o a roupas formais e também a trajes coloridos em aparições reconcilatórias.',
    'Viveu mais de noventa anos e deixou legado político e social duradouro.',
    'Seu nome é referência em programas e campanhas por direitos humanos.',
    'Foi figura central no fim de um regime oficial de discriminação institucional.',
    'Discursos e frases suas são citados em contextos de justiça e igualdade.',
    'É considerado um dos principais nomes da luta pelos direitos civis no século XX.'
  ],
  24: [
    'Dramaturgo e poeta cuja obra floresceu entre o final do século XVI e início do XVII.',
    'Escreveu tragédias, comédias e peças históricas que viraram clássicos mundiais.',
    'Teve forte ligação com um teatro famoso às margens do Tâmisa.',
    'Nasceu em uma pequena cidade inglesa e trabalhou na capital em temporadas.',
    'Escreveu uma coleção numerada de poemas sobre amor e juventude.',
    'Muitas frases suas entraram para o inglês cotidiano e são frequentemente citadas.',
    'Suas peças abordam reinos, vingança, intriga e paixões humanas profundas.',
    'Duas de suas obras mais célebres tratam de um casal trágico e de um príncipe dinamarquês.',
    'O teatro associado ao seu grupo foi reconstruído e virou atração cultural turística.',
    'Seus sonetos geraram debates sobre autoria e destinatário misterioso.',
    'Viveu e escreveu na era elisabetana e jacobina da Inglaterra.',
    'Sua produção influenciou a literatura, o teatro e o cinema por séculos.',
    'Documentos da época registram contratos e acordos ligados ao seu trabalho teatral.',
    'Muitos acadêmicos discutem a autoria de algumas peças atribuídas a ele.',
    'Adaptações modernas transpõem suas histórias para cenários contemporâneos.',
    'Seu teatro original tinha formato de globo e recebia público em pé.',
    'É frequentemente referido apenas pelo sobrenome na crítica literária.',
    'Peças suas são encenadas em escolas e teatros pelo mundo todo.',
    'Sua língua original é o inglês Early Modern, estudado em cursos de literatura.',
    'É considerado o principal dramaturgo da língua inglesa.'
  ],
  25: [
    'Pioneira na aviação cuja carreira se destacou nas décadas de 1920 e 1930.',
    'Quebrou barreiras de gênero ao realizar voos solo de grande repercussão pública.',
    'Promoveu o interesse público por voos e pela aviação comercial.',
    'Era conhecida por dar palestras e escrever sobre suas experiências de voo.',
    'Tentou completar uma volta ao mundo em rota próxima ao equador e desapareceu durante a tentativa.',
    'Seu desaparecimento gerou várias teorias e expedições de busca subsequentes.',
    'Pilotou aeronaves monoplanas de asa longa em travessias oceânicas.',
    'Foi condecorada e recebeu prêmios por feitos pioneiros na aviação.',
    'Seu estilo de vestuário público era associado à imagem prática de pilotos da época.',
    'A última comunicação pública sugeriu problemas de navegação sobre o oceano.',
    'Sua história inspirou livros, filmes e documentários sobre exploração aérea.',
    'Colaborou com organizações que incentivavam mulheres em profissões técnicas.',
    'Sua visibilidade ajudou a tornar a aviação mais popular entre o público leigo.',
    'Nacionalidade norte-americana e figura reconhecida internacionalmente.',
    'O desaparecimento ocorreu no Pacífico durante a década de 1930.',
    'Várias instituições e museus preservam objetos ligados à sua trajetória.',
    'É frequentemente citada como ícone de coragem e espírito aventureiro feminino.',
    'A tentativa final ocorreu em 1937 e permanece envolta em mistério.',
    'Seu legado inclui incentivo à presença feminina em áreas técnicas e de navegação aérea.',
    'É lembrada como uma das primeiras mulheres piloto com fama mundial.'
  ],
  26: [
    'Elevado sobre uma grande cidade brasileira, observado por milhões de visitantes.',
    'Escultura monumental com braços abertos formando um abraço simbólico.',
    'Erguido no alto de um morro que domina a baía onde se vê um grande Pão de Açúcar.',
    'Obra construída em estilo artístico do início do século XX, com influência internacional.',
    'É um ponto de peregrinação turística e motivo frequente em fotografias de cartões-postais.',
    'Fica numa cidade famosa por praias, morros e carnaval.',
    'A montagem envolveu engenheiros e artistas de diferentes nacionalidades.',
    'É geralmente acessível por um trem de turismo ou por trilhas até seu platô.',
    'Possui iluminação especial à noite que realça sua silhueta sobre a cidade.',
    'Foi inaugurado no primeiro terço do século XX e passou por restaurações ao longo do tempo.',
    'Sua imagem é símbolo de recepção e acolhimento para visitantes do país.',
    'Fica no estado do Rio de Janeiro, em área urbana contígua à baía.',
    'É retratado em filmes, músicas e campanhas turísticas nacionais.',
    'A vista do local inclui uma famosa praia e um estádio mundialmente conhecido.',
    'Muitos passeios combinam visita ao morro com outras atrações turísticas da cidade.',
    'Os braços abertos formam quase um lençol que acolhe a paisagem ao redor.',
    'O monumento está sobre o morro do Corcovado.',
    'É uma estátua de grande porte que domina o horizonte da cidade costeira.',
    'Associado à cidade do Rio de Janeiro e ao país Brasil.',
    'É o monumento cristão de braços abertos mais famoso do país.'
  ],
  27: [
    'Capital europeia conhecida pela influência nas artes, moda e gastronomia.',
    'Cortada por um rio famoso que serpenteia pela cidade em ambos os lados.',
    'Possui um monumento metálico inaugurado no final do século XIX que virou seu cartão-postal.',
    'Lar de um museu que abriga milhares de obras, incluindo uma pintura muito famosa sem moldura original.',
    'Bairros como Montmartre e Le Marais são referências culturais locais.',
    'A língua oficial do país é o francês.',
    'A avenida Champs-Élysées é conhecida por desfiles e eventos públicos.',
    'É famosa por cafés, pâtisseries e pela vida noturna elegante.',
    'Tem uma praça central com uma catedral gótica e vitrais impressionantes em seu entorno.',
    'Sedia exposições e feiras de moda que ditam tendências globais.',
    'A culinária local valoriza pães, queijos e vinhos como ícones gastronômicos.',
    'Há uma colina com uma basílica branca que oferece vista panorâmica da cidade.',
    'Seus museus atraem milhões de visitantes por ano.',
    'É conhecida como a "Cidade das Luzes" em muitos idiomas.',
    'Um grande centro cultural e científico do país fica nessa capital.',
    'Recebe milhões de turistas e é ponto de partida para viagens pela região norte da França.',
    'Seu nome é associado a romances, artes e à revolução cultural europeia.',
    'A Torre mencionada foi projetada inicialmente como estrutura temporária para uma exposição universal.',
    'É a capital da França e símbolo de charme e elegância europeia.',
    'Começa com P e tem cinco letras no nome em português.'
  ],
  28: [
    'Sistema natural formado por estruturas calcárias que abrigam enorme biodiversidade marinha.',
    'Localizado ao longo da costa nordeste de um grande país da Oceania.',
    'Reconhecido como o maior conjunto de recifes do planeta, visível até do espaço em imagens específicas.',
    'Destino popular para mergulho autônomo e turismo de snorkel.',
    'Sofre ameaças recentes relacionadas à elevação da temperatura e à acidez dos oceanos.',
    'Abriga corais, peixes tropicais e tartarugas marinhas em ecossistemas complexos.',
    'Suas formações crescem lentamente e criam paisagens submarinas coloridas.',
    'É Patrimônio Mundial e alvo de estudos científicos sobre conservação marinha.',
    'Muitas ilhas e cayos fazem parte do conjunto associado a essas estruturas recifais.',
    'Operadores turísticos oferecem passeios de barco saindo de cidades costeiras próximas.',
    'Grande extensão costeira que se estende por centenas de quilômetros.',
    'Importante para a pesca local e para o equilíbrio ecológico regional.',
    'Seu país é conhecido por vastas planícies áridas no interior e por cidades costeiras vibrantes.',
    'Os recifes atuam como barreira natural protegendo áreas costeiras de ondas e tempestades.',
    'Pesquisas monitoram eventos de branqueamento que afetam a saúde do ecossistema.',
    'É associada à Austrália e ao turismo ecológico marinho.',
    'Grande área marinha que atrai cientistas e viajantes preocupados com o ambiente.',
    'É o maior sistema de recifes de corais do mundo.',
    'Nome começa com G e inclui as palavras "Barreira" e "Coral" em português.',
    'Conhecido como Grande Barreira de Coral.'
  ],
  29: [
    'Ilha famosa por esculturas monolíticas com rostos alongados.',
    'Localizada no Pacífico, com forte herança da cultura polinésia local.',
    'As estátuas são chamadas de moai e foram erguidas por povos antigos da ilha.',
    'A escrita local tradicional inclui um sistema de símbolos chamado rongorongo (associado à ilha).',
    'Visitantes chegam por via aérea ou por embarcação para explorar sítios arqueológicos.',
    'Suas esculturas têm tamanhos variados, algumas impressionantemente grandes.',
    'A ilha tem nome ligado a uma celebração religiosa na tradição europeia, segundo exploradores.',
    'A localização isolada contribuiu para o desenvolvimento de uma cultura única ao longo dos séculos.',
    'Pesquisas arqueológicas buscam entender a logística de transporte das grandes estátuas.',
    'É um destino símbolo de mistérios sobre as capacidades de sociedades pré-industriais.',
    'Suas paisagens incluem campos abertos e crateras vulcânicas adaptadas ao turismo.',
    'A ilha faz parte de um país associado politicamente ao Pacífico sudeste.',
    'A preservação das estátuas é desafio devido à erosão e às alterações ambientais.',
    'A ilha é também conhecida pelo nome Rapa Nui na língua local.',
    'Tem relação histórica com navegadores europeus que documentaram a existência dos moai.',
    'A cultura local realiza festivais que celebram sua herança ancestral.',
    'As estátuas estão distribuídas em locais chamados ahus, plataformas cerimoniais.',
    'Fica isolada no Pacífico, entre a Polinésia e a costa da América do Sul.',
    'O nome em português inclui as palavras "Ilha" e uma referência à data cristã.',
    'É mundialmente famosa pelos moai e pelo nome Ilha de Páscoa.'
  ],
  30: [
    'Metrópole norte-americana conhecida por arranha-céus e diversidade cultural.',
    'Tem um distrito financeiro famoso que abriga importantes bolsas e sedes de empresas.',
    'Uma ilha famosa abriga uma figura que foi um presente de outra nação e recebe visitantes por ferry.',
    'Times Square e seus letreiros luminosos tornam parte da cidade famosa pela vida noturna e espetáculos.',
    'Bairros como Brooklyn, Manhattan e Queens têm identidades culturais distintas.',
    'A cidade é referência em música, teatro (especialmente na Broadway) e artes performáticas.',
    'Central Park funciona como um grande pulmão verde no coração de uma ilha urbana densamente edificada.',
    'Táxis amarelos e metrô extenso ajudam a caracterizar o transporte local.',
    'É ponto de chegada de imigrantes há várias gerações e mantém forte presença multicultural.',
    'O skyline com arranha-céus se tornou referência em filmes e fotografias globais.',
    'A cidade sediou marcos históricos e eventos culturais que influenciaram o mundo.',
    'A gastronomia local reúne opções de todas as partes do planeta em bairros específicos.',
    'Wall Street representa o poder financeiro que tem parte importante na identidade local.',
    'É famosa por museus de classe mundial e instituições de ensino superior renomadas.',
    'O nome em português tem duas palavras e é frequentemente abreviado apenas pela sigla NY.',
    'Recebe milhões de turistas por ano, atraídos por shows, compras e pontos icônicos.',
    'Sua área central inclui uma avenida famosa por desfiles e desfiles de moda.',
    'Alguns dos prédios mais altos do país compõem seu horizonte urbano moderno.',
    'É a cidade mais populosa dos Estados Unidos e um símbolo global de urbanidade.',
    'Começa com N e termina com K no nome em português: Nova York.'
  ],
  31: [
    'Evento que provocou encontro duradouro entre povos de dois grandes continentes separados por oceano.',
    'Expedição patrocinada por monarcas ibéricos em busca de rota ocidental para as Índias.',
    'Viagens de navio cruzaram o Atlântico rumo a ilhas caribenhas desconhecidas para europeus na época.',
    'A expedição partiu do porto com caravelas e tripulações pequenas para padrões modernos.',
    'Ano associado ao início da presença europeia recorrente nas Américas.',
    'Coincidiu com o término de uma guerra de reconquista na península onde estavam os reis patrocinadores.',
    'Mudou profundamente mapas, rotas comerciais e trocas biológicas entre continentes.',
    'Marcou o começo de colonizações e do tráfico transatlântico que moldariam séculos seguintes.',
    'As coroa patrocinadora era formada por um rei e uma rainha famosos da história espanhola.',
    'Antes desse ano, mapas europeus não registravam ilhas agora conhecidas como parte do Novo Mundo.',
    'A expedição é frequentemente atribuída a um navegador genovês a serviço da monarquia ibérica.',
    'O desembarque ocorreu em ilhas tropicais hoje associadas ao Caribe.',
    'Este ano é frequentemente citado como marco do "descobrimento" europeu das Américas.',
    'Documentos da época registram acordos reais que financiaram a viagem atlântica.',
    'O episódio abriu caminho para consequente troca de plantas, animais e doenças entre hemisférios.',
    'Museus e livros de história citam esse ano como referência para a era das grandes navegações.',
    'Para alguns povos, é também o início de um período de profundas transformações e perdas.',
    'Exploradores de outras nações europeias seguiram a mesma rota nas décadas seguintes.',
    'É o ano associado ao primeiro contato europeu registrado nas Américas por essa expedição específica.',
    'É lembrado como o ano da viagem de Cristóvão Colombo que chegou às Américas.'
  ],
  32: [
    'Ano que marcou o início de um conflito global que mobilizou grandes potências europeias.',
    'O estopim envolveu um ataque que aconteceu durante uma visita oficial em Sarajevo.',
    'Blocos de alianças militares transformaram uma ruptura regional em guerra continental.',
    'Foi seguido por quatro anos de combates que envolveram trincheiras e frente ocidental estagnada.',
    'Novas tecnologias militares e táticas de guerra tiveram impacto terrível nas baixas humanas.',
    'Navios, aviões e artilharia desempenharam papéis cruciais no desenrolar do conflito inicial.',
    'Movimentos nacionalistas e disputas imperialistas foram causas subjacentes importantes.',
    'O conflito redesenhou mapas e levou ao colapso de impérios antigos na Europa.',
    'Muitos jovens foram convocados em massa e enviados para frentes de batalha longínquas.',
    'A guerra resultou em mudanças geopolíticas que prepararam o terreno para conflitos posteriores.',
    'Memoriais e cemitérios em várias regiões europeias lembram as batalhas desse período.',
    'O ano é lembrado por uma sequência de declarações de guerra entre estados centrais e aliados.',
    'Tratados e reorganização territorial no pós-guerra tiveram efeitos duradouros no mapa europeu.',
    'Literatura e poesia da época e posteriores trataram da dureza das trincheiras e da vida militar.',
    'O assassinato do arquiduque Francisco Ferdinando é frequentemente citado como causa imediata.',
    'O conflito foi o primeiro de escala industrial envolvendo conscrições em massa.',
    'A guerra levou a inovações em medicina de guerra e logística militar.',
    'Centenas de milhares perderam a vida nos primeiros anos do conflito e milhões mais ao longo dele.',
    'Historiadores marcam esse ano como o começo da Primeira Guerra Mundial.',
    'É o ano do assassinato em Sarajevo que desencadeou a Primeira Guerra Mundial.'
  ],
  33: [
    'Ano que marcou o fim de um grande conflito global e o enterro de regimes totalitários na Europa e Ásia.',
    'Testes nucleares e o uso de armas atômicas mudaram para sempre a percepção sobre destruição em massa.',
    'Conferências entre aliados redesenharam o mapa político e iniciaram tentativas de reconstrução.',
    'Forças militares liberaram campos e prisões que revelaram crimes de guerra amplamente divulgados.',
    'A criação de uma organização internacional com objetivo de evitar novos conflitos ocorreu nesse período.',
    'O líder de uma potência europeia derrotada morreu por suicídio antes do fim oficial das hostilidades no continente.',
    'O emprego de duas bombas nucleares ao final do conflito no Pacífico precipitou a rendição de um país.',
    'Territórios sob ocupação foram reordenados e julgamentos por crimes atrozes foram iniciados.',
    'Milhões de deslocados e refugiados começaram um processo longo de repatriação e reconstrução.',
    'A autoridade dos vencedores organizou conferências que definiram zonas de ocupação e esferas de influência.',
    'A fundação de uma organização global para a paz e cooperação internacional data desse momento.',
    'A libertação de campos de concentração tornou públicas evidências de genocídio em larga escala.',
    'Muitas cidades devastadas deram início a projetos de restauração urbana e memorialização.',
    'O uso das bombas acelerou o fim das hostilidades no teatro do Pacífico.',
    'O ano é lembrado como ponto de virada que encerrou a Segunda Guerra Mundial.',
    'Documentos e fotografias daquele período mostram cenas de rendição e celebração em vários países.',
    'Líderes aliados assinaram atos que formalizaram a rendição dos agressores.',
    'A década que se seguiu foi marcada por processo de julgamento e reconstrução internacional.',
    'Este é o ano amplamente reconhecido como o término da Segunda Guerra Mundial.',
    'É o ano em que ocorreram as capitulações que encerraram o conflito global.'
  ],
  34: [
    'Ano marcado por eventos cruciais da luta por direitos civis em uma grande potência ocidental.',
    'Um discurso famoso sobre um sonho de igualdade foi proferido diante de multidões em uma capital nacional.',
    'Ao longo do ano, manifestações e marchas por igualdade ganharam ampla cobertura midiática.',
    'Também foi o ano em que um líder político foi assassinado em plena via pública, gerando comoção mundial.',
    'O assassinato ocorreu durante uma viagem oficial pelas ruas de uma cidade americana.',
    'Movimentos culturais e musicais da época começaram a deixar marcas duradouras na juventude.',
    'Televisão e rádio ajudaram a difundir imagens que mobilizaram opinião pública globalmente.',
    'O presidente assassinado era jovem na função e simbolizava esperança para uma geração.',
    'Esse ano consolidou a figura de um pastor e ativista que se tornou símbolo do movimento por igualdade racial.',
    'Uma marcha histórica reuniu líderes e comunidades para exigir direitos e reformas legislativas.',
    'Fotografias do momento mobilizador circulam até hoje em materiais educativos e museus.',
    'A tragédia política e os protestos civis marcaram profundamente a memória coletiva daquele período.',
    'Séries biográficas e documentários revisitavam ambos os acontecimentos décadas depois.',
    'O discurso citado ficou conhecido por frases que pedem liberdade, justiça e irmandade.',
    'O evento do assassinato ocorreu em novembro durante uma caravana presidencial.',
    'O movimento pelos direitos civis conseguiu grandes centralizações de apoio naquele ano.',
    'A confluência entre política, música e ativismo foi intensa naquele período histórico.',
    'Livros de história tratam desse ano como ponto central das lutas sociais nos EUA.',
    'É o ano do assassinato do presidente John F. Kennedy e do discurso "I have a dream" de Martin Luther King.',
    'Este ano é frequentemente lembrado por ambos os marcos: o discurso de MLK e o assassinato de JFK.'
  ],
  35: [
    'Ano associado à virada do milênio e a grandes celebrações de passagem de século ao redor do mundo.',
    'Houve elevada atenção a um problema de computadores relacionado à representação de datas que poderia causar falhas globais.',
    'Uma grande cidade australiana sediou os Jogos Olímpicos de Verão nesse ano.',
    'O mundo viu festas públicas, queimas de fogos e eventos transmitidos ao vivo em escala global.',
    'Setores de tecnologia e empresas da internet viviam momentos de grande especulação e também de correções de mercado.',
    'Muitos governos e empresas investiram em contingência para evitar interrupções tecnológicas na virada.',
    'Programas e serviços online estavam em ascensão, mas preocupações sobre estabilidade cresciam.',
    'O ano representou simbolicamente o começo de uma nova década e o fim de outra milenar.',
    'Alguns veículos de mídia publicaram retrospectivas do século que se encerrava.' ,
    'A gestão de grandes eventos e turismo urbano foi alvo de destaque por causa das comemorações.',
    'Relatórios econômicos e análises discutiam a bolha das empresas digitais daquele período.',
    'A cidade-sede das Olimpíadas recebeu delegações e atletas de todo o mundo, com cerimônias marcantes.',
    'Houve atenção internacional sobre se infraestruturas críticas suportariam o aumento de demanda na virada.',
    'Filmes e livros da época capturaram a sensação de transição histórica vivida globalmente.',
    'Muitos lembram desse ano como uma passagem celebrada, ainda que carregada de incertezas tecnológicas.',
    'Sistemas bancários, telefônicos e de aviação fizeram verificações antes da mudança de data global.',
    'A preocupação conhecida como "bug do milênio" mobilizou equipes de TI pelo planeta.',
    'É o ano das celebrações do fim do segundo milênio e início do terceiro milênio no calendário gregoriano.',
    'Algumas empresas de internet sofreram correções de mercado nesse período histórico.',
    'É o ano comemorado mundialmente como a virada para o ano 2000.'
  ],
  36: [
    'Instrumento concebido para medir e indicar passagem de intervalos. ',
    'Tem versões mecânicas, automáticas e eletrônicas.',
    'Pode ser usado preso ao pulso ou como peça de bolso antigamente.',
    'Possui disco ou mostrador com marcas que representam unidades regulares.',
    'Em versões analógicas, costuma ter ponteiros para indicar horas, minutos e segundos.',
    'Alguns modelos têm coroa lateral para ajuste manual do mecanismo.',
    'Modelos sofisticados exibem complicações como cronógrafo e fase lunar.',
    'Pulseiras e braceletes são acessórios que acompanham a peça no uso diário.',
    'É usado tanto por praticantes de esportes quanto por executivos e pessoas comuns.',
    'A precisão depende de componentes internos como molas e engrenagens ou circuitos eletrônicos.',
    'Antes de celulares, era o principal meio pessoal para saber as horas instantaneamente.',
    'Relógios de pulso populares surgiram amplamente a partir do início do século XX.',
    'Modelos clássicos podem ser herdados por gerações como um objeto sentimental.',
    'Painéis digitais exibem números quando o mecanismo é eletrônico.',
    'Alguns tipos sincronizam com sinais de rádio ou satélites para alta precisão.',
    'Termos como GMT e cronógrafo estão ligados a funcionalidades desse objeto.',
    'Pequenas marcas e índices ajudam a ler o tempo com rapidez no mostrador.',
    'Fabricantes famosos valorizam acabamentos, materiais e calibres internos.',
    'Usado como acessório de moda e instrumento funcional ao mesmo tempo.',
    'Serve para marcar horas, minutos e segundos no dia a dia.'
  ],
  37: [
    'Aparelho projetado para capturar imagens estáticas ou em movimento.',
    'Originalmente usava filmes químicos; hoje há sensores eletrônicos dominantes.',
    'Componentes-chave incluem lente, obturador e diafragma.',
    'Permite controlar abertura, velocidade e sensibilidade para regular exposição.',
    'Pode ser compacta, reflex (com espelho) ou sem espelho, em versões profissionais e amadoras.',
    'A distância focal da lente afeta campo de visão e nível de aproximação aparente.',
    'Tripés, flashes e filtros são acessórios comuns para melhorar resultados.',
    'Fotógrafos profissionais e entusiastas a utilizam em estúdio e ao ar livre.',
    'A qualidade da lente costuma ser tão importante quanto a do sensor ou filme.',
    'Termos como ISO, obturador e foco automático relacionam-se ao seu uso técnico.',
    'Alguns modelos permitem troca de lentes para diferentes tipos de enquadramento.',
    'A evolução tecnológica permitiu ver fotos instantaneamente em telas digitais.',
    'Antes era comum revelar filmes em laboratórios; hoje imprime-se a partir de arquivos digitais.',
    'Usada tanto para registros pessoais quanto para imprensa, ciência e arte.',
    'Técnicas como longa exposição e panning produzem efeitos especiais de movimento.',
    'Modelos antigos com filme são colecionáveis por entusiastas e historiadores.',
    'Em eventos, profissionais usam equipamentos mais robustos para garantir resultados.',
    'Apps de celular trouxeram democratização, mas equipamentos dedicados mantêm vantagens óticas.',
    'A captura de imagens depende de controlar luz e tempo de exposição.',
    'É o aparelho que registra fotografias e vídeos.'
  ],
  38: [
    'Veículo movido por energia humana e eficiente para curtas e médias distâncias.',
    'Possui duas rodas alinhadas, quadro, guidão e assento ajustável.',
    'O movimento é acionado por pedais ligados a uma transmissão por corrente ou correia.',
    'Mudanças de marcha ajudam a adaptar esforço em subidas e descidas.',
    'Usada tanto para transporte urbano quanto para lazer e competições esportivas.',
    'Modelos variam entre urbanos, de estrada e montanha, com geometrias diferentes.',
    'A segurança inclui capacete, luzes e sinalização para tráfego misto com veículos motorizados.',
    'A prática regular traz benefícios cardiovasculares e de condicionamento físico.',
    'Algumas versões elétricas adicionam motor auxiliar, mantendo pedais.',
    'Peças como freios, cubos e pneus influenciam desempenho e conforto.',
    'História de uso envolve invenções e aperfeiçoamentos na transmissão e fabricação de quadros.',
    'É comum em programas de mobilidade urbana e ciclos de compartilhamento em cidades.',
    'Passeios ciclísticos e corridas famosas mobilizam grandes públicos em várias cidades.',
    'Transporta-se em racks de carro e em alguns trens urbanos dobráveis.' ,
    'A forma mais básica tem selim, pedais e um par de rodas, sem motor próprio.',
    'Manutenção inclui lubrificação da corrente e ajuste de marchas e freios.',
    'Fabricantes criam modelos específicos para usos profissionais e recreativos.',
    'Usada desde o século XIX, tornou-se ícone de independência de deslocamento pessoal.',
    'É um meio de transporte sustentável e amplamente praticado no mundo.',
    'Tem duas rodas, pedais e é movida pelo esforço do usuário.'
  ],
  39: [
    'Máquina eletrônica programável capaz de processar dados e executar instruções.',
    'Composta por unidade de processamento, memória e dispositivos de entrada/saída.',
    'Pode variar de aparelhos pessoais compactos a grandes servidores em centros de dados.',
    'Executa programas que vão de editores de texto a sistemas operacionais complexos.',
    'Armazena informação em estruturas binárias e usa linguagens para comunicação humana-máquina.',
    'Componentes-chave incluem CPU, RAM, disco (ou SSD) e placas de expansão.',
    'Periféricos como teclado, mouse e monitor são formas comuns de interação.',
    'Rede e internet dependem de máquinas desse tipo para hospedar serviços e trocar pacotes.',
    'A evolução passou de válvulas a transistores e hoje a microprocessadores muito rápidos.',
    'Tarefas como cálculos complexos, edição multimídia e navegação são exemplos de uso diário.',
    'Programas maliciosos e vírus são riscos que exigem cuidados e atualizações.',
    'Sistemas operacionais gerenciam recursos e processos simultâneos em multitarefa.',
    'A miniaturização permitiu que versões portáteis mantivessem grande parte das funcionalidades.',
    'Diversas áreas da ciência e indústria dependem desses dispositivos para automação e análise.',
    'O usuário interage por interfaces gráficas ou linhas de comando dependendo do ambiente.',
    'Armazenamento em nuvem amplia capacidades além do hardware local.',
    'Termos como CPU, RAM, GPU e SSD definem características de desempenho.',
    'A computação moderna transformou comunicação, trabalho e entretenimento globalmente.',
    'É a máquina eletrônica que processa dados e executa programas.'
  ],
  40: [
    'Bebida produzida a partir de grãos torrados que cresce em regiões tropicais e subtropicais.',
    'O fruto colhido é conhecido como cereja que apresenta a semente utilizada para a bebida.',
    'A torra influencia aromas, sabores e intensidade do produto final.',
    'Consumida globalmente em várias formas: filtrada, expresso, coada, entre outras.',
    'Contém uma substância estimulante que afeta atenção e sonolência.',
    'Plantas comercialmente cultivadas pertencem a gêneros que incluem várias espécies.',
    'Países produtores se destacam por altitude, solo e clima que definem perfis de acidez e corpo.',
    'Métodos de preparo caseiros e profissionais variam conforme tradição e equipamento.',
    'Cafés especiais são avaliados por notas sensoriais como frutada, floral ou achocolatada.',
    'Os grãos passam por processos de secagem, beneficiamento e classificação antes da venda.',
    'É bebida associada a rituais matinais e encontros sociais em muitos lugares.',
    'Cafeterias oferecem bebidas de diferentes preparos e graus de intensidade.',
    'A cultura do produto inspirou música, literatura e economia em regiões produtoras.',
    'O serviço expresso requer pressão e moagem adequada para extrair sabores concentrados.',
    'Coletores e cooperativas locais participam da cadeia até o consumo final.',
    'Xícaras e canecas servem como recipientes tradicionais para o consumo diário.',
    'A palavra em português nomeia tanto a bebida quanto a planta em contextos distintos.',
    'A bebida é frequentemente associada a pausas, produtividade e convívio social.',
    'Muito apreciada em todo o mundo, tem variações de preparação regionais notáveis.',
    'É a bebida resultante da infusão de sementes torradas de uma planta cultivada em climas tropicais.'
  ],
}

export const TIPS = Object.entries(CARD_TIPS).flatMap(([cardId, tips]) =>
  tips.map((text, index) => ({
    id: (Number(cardId) - 1) * 20 + index + 1,
    cardId: Number(cardId),
    text,
    number: index + 1,
  })),
)