const CARD_TIPS: Record<number, string[]> = {
  1: [
    'Meu trabalho ficou adormecido por muitas decadas.',
    'Vivi na Inglaterra no seculo XIX.',
    'Nasci em uma familia ligada a poesia romantica.',
    'Escrevi sobre uma maquina que ainda nem existia de fato.',
    'Minha contribuicao ficou famosa muito depois da minha morte.',
    'Trabalhei com tabelas, simbolos e logica.',
    'Sou lembrada em debates sobre mulheres na tecnologia.',
    'Meu sobrenome de casada nao era o mesmo do meu pai famoso.',
    'Trabalhei com um matematico inventor de uma maquina analitica.',
    'Anotei um metodo para calcular numeros de Bernoulli.',
    'Esse metodo e considerado por muitos um programa pioneiro.',
    'Meu texto ia alem de simples contas numericas.',
    'Vi potencial de manipular tambem musica e linguagem por simbolos.',
    'Fui chamada de encantadora dos numeros por um colega.',
    'Meu primeiro nome aparece em uma linguagem de programacao.',
    'Sou frequentemente citada como pioneira da computacao.',
    'Meu pai foi Lord Byron.',
    'Meu parceiro intelectual foi Charles Babbage.',
    'Meu trabalho foi feito para a Engine Analitica.',
    'Meu nome completo une Ada a um sobrenome aristocratico ingles.',
  ],
  2: [
    'Virei simbolo de excelencia no esporte do meu pais.',
    'Competi em uma modalidade de velocidade extrema.',
    'Fiquei famoso por concentracao intensa antes das disputas.',
    'Usei capacete com cores muito reconheciveis.',
    'Tive grande rivalidade com um frances multicampeao.',
    'Meu talento apareceu cedo em categorias de base.',
    'Corri por equipes tradicionais europeias.',
    'Meu estilo em pista misturava agressividade e precisao.',
    'Ganhei provas em condicoes de chuva consideradas impossiveis.',
    'Conquistei tres titulos mundiais.',
    'Meu nome batiza avenidas, escolas e institutos.',
    'Uma vitoria marcante veio no Japao no fim dos anos 80.',
    'No Brasil, domingos de corrida ficaram associados a mim.',
    'Minha bandeira nacional aparecia no cockpit apos vitorias.',
    'Muitos me chamavam de idolo nacional.',
    'Minha carreira foi interrompida tragicamente em Imola.',
    'Aconteceu durante um Grande Premio em 1994.',
    'Sou lembrado como lenda da Formula 1.',
    'Meu primeiro nome e Ayrton.',
    'Meu nome completo une Ayrton a um sobrenome de quatro letras.',
  ],
  3: [
    'Sou uma mente ficticia extremamente analitica.',
    'Resolvo misterios com observacao minuciosa.',
    'Atuo em historias ambientadas na Inglaterra vitoriana.',
    'Tenho um companheiro medico que narra varios casos.',
    'Meu criador era um escritor e medico escoces.',
    'Costumo perceber detalhes que outros ignoram.',
    'Tenho um inimigo intelectual de grande reputacao criminosa.',
    'Ja fui retratado em livros, filmes e series.',
    'Meu endereco literario ficou famoso mundialmente.',
    'Uso raciocinio dedutivo como marca principal.',
    'Sou associado a lupa e cachimbo em representacoes classicas.',
    'Tenho perfil frio, logico e pouco paciente.',
    'Meu parceiro de investigacoes se chama Watson.',
    'Meu arqui-inimigo e Moriarty.',
    'Moro na Baker Street, numero 221B.',
    'Fui criado por Arthur Conan Doyle.',
    'Sou um detetive consultor.',
    'Meu nome proprio e o mesmo de um famoso ator americano.',
    'Meu sobrenome e Holmes.',
    'Meu nome completo junta um prenome classico a Holmes.',
  ],
  4: [
    'Transformei dor pessoal em arte marcante.',
    'Minha obra mistura realidade, simbolismo e autobiografia.',
    'Nasci e vivi no Mexico.',
    'Meu rosto se tornou icone cultural global.',
    'Pintei muitos autorretratos ao longo da vida.',
    'Uma limitacao fisica influenciou meu processo criativo.',
    'Cores fortes e elementos da cultura popular mexicana aparecem no meu trabalho.',
    'Fui ligada a movimentos politicos de esquerda.',
    'Meu relacionamento com outro pintor famoso foi intenso e turbulento.',
    'Minha casa azul virou museu.',
    'Usei roupas tradicionais como afirmacao identitaria.',
    'Minha sobrancelha marcante virou assinatura visual.',
    'Tive um acidente de onibus na juventude.',
    'Meu companheiro foi Diego Rivera.',
    'Minha obra ganhou enorme reconhecimento apos minha morte.',
    'Sou referencia em debates sobre feminismo e representacao.',
    'Meu primeiro nome tem cinco letras.',
    'Meu sobrenome comeca com K.',
    'Sou Frida.',
    'Meu nome completo junta Frida a um sobrenome curto de origem germanica.',
  ],
  5: [
    'Trabalho quando muitos estao correndo para longe.',
    'Meu dia a dia exige preparo fisico e emocional.',
    'Atuo em equipes coordenadas por radios e protocolos.',
    'Lido com emergencias urbanas e residenciais.',
    'Uso equipamentos de protecao pesados.',
    'Minha rotina inclui treinamentos constantes.',
    'Entro em locais com calor extremo e baixa visibilidade.',
    'Tambem ajudo em enchentes, resgates e acidentes.',
    'Meu veiculo costuma chamar atencao nas ruas.',
    'Mangueiras e escadas estao entre minhas ferramentas.',
    'Capacete e roupa antichamas fazem parte do uniforme.',
    'Posso atuar em salvamento em altura.',
    'Muitos me chamam em situacoes de curto-circuito e fumaca.',
    'Atendo ligacoes de emergencia 24 horas.',
    'Minha missao principal e proteger vidas.',
    'Sou associado a sirenes e quartel.',
    'Combato incendios.',
    'Faco parte do corpo de salvamento.',
    'Minha profissao comeca com B.',
    'Minha profissao e a primeira lembrada quando se fala em apagar fogo.',
  ],
  6: [
    'Sou um dos maiores viloes da cultura pop.',
    'Minha presenca e ligada a poder e medo.',
    'Uso vestimenta escura quase o tempo todo.',
    'Tenho ligacao familiar central para a saga em que apareco.',
    'Fui treinado em uma ordem de guerreiros misticos.',
    'Troquei meu antigo caminho por um lado sombrio.',
    'Minha voz grave e inconfundivel em varias versoes.',
    'Carrego uma arma de energia em duelos.',
    'Meu visual inclui mascara e respiracao mecanica.',
    'Sirvo a um lider autoritario de um imperio galactico.',
    'Meu passado inclui talento excepcional com a Forca.',
    'Pilotei naves e cacas em batalhas espaciais.',
    'Minha historia envolve queda, culpa e redencao.',
    'Tenho relacao direta com Luke e Leia.',
    'Meu nome de nascimento era Anakin.',
    'Sou do universo de Star Wars.',
    'Meu sobrenome e Vader.',
    'Meu primeiro nome comeca com D.',
    'Meu nome completo combina um titulo curto com Vader.',
    'Sou o pai de Luke Skywalker.',
  ],
  7: [
    'Fui construida em altitude elevada.',
    'Minha origem envolve um grande imperio pre-colombiano.',
    'Fico em uma regiao montanhosa da America do Sul.',
    'Fiquei escondida para boa parte do mundo por seculos.',
    'Minhas estruturas de pedra impressionam pela engenharia.',
    'Nao fui erguida com argamassa comum entre blocos.',
    'Sou cercada por picos e neblina frequente.',
    'Muitos visitantes chegam de trem e trilhas.',
    'Meu local e associado a lama e alpacas da regiao andina.',
    'Sou considerada patrimonio mundial.',
    'Meu nome em quechua tem relacao com montanha antiga.',
    'Fico perto de Cusco.',
    'Estou no Peru.',
    'Sou uma das paisagens mais fotografadas do continente.',
    'Meu acesso classico inclui a Trilha Inca.',
    'Fui revelada ao publico internacional por Hiram Bingham.',
    'Sou uma antiga cidade inca.',
    'Meu nome comeca com M.',
    'Meu nome termina com Picchu.',
    'Meu nome completo combina duas palavras de origem quechua.',
  ],
  8: [
    'Sou uma metropole que mistura tradicao e tecnologia.',
    'Tenho bairros com ritmos e estilos muito diferentes.',
    'Minha rede de transporte e conhecida pela eficiencia.',
    'Fico em um arquipelago no leste da Asia.',
    'Sou enorme em populacao e influencia economica.',
    'Neons e telas gigantes marcam algumas das minhas areas.',
    'Tambem tenho templos antigos e jardins serenos.',
    'Sediar megaeventos internacionais faz parte da minha historia.',
    'Minha culinaria e reverenciada no mundo inteiro.',
    'Tenho cruzamentos famosos com fluxo intenso de pedestres.',
    'Sou referencia em eletronicos, games e cultura pop.',
    'Na primavera, cerejeiras atraem multidoes.',
    'Meu pais usa iene como moeda.',
    'Fui sede dos Jogos Olimpicos em 1964 e novamente decadas depois.',
    'Meu antigo nome oficial foi Edo.',
    'Sou a capital do Japao.',
    'Meu nome em portugues leva acento na vogal final.',
    'Comeco com T.',
    'Termino com quio.',
    'Sou a capital japonesa conhecida por tecnologia e tradicao.',
  ],
  9: [
    'Sou vastidao natural de escala continental.',
    'Abrigo biodiversidade considerada unica no planeta.',
    'Meus rios formam uma rede gigantesca.',
    'Influencio ciclos de chuva em varias regioes.',
    'Sou tema central em discussoes ambientais globais.',
    'Muitos povos originarios vivem em meu territorio.',
    'Minha vegetacao e predominantemente tropical.',
    'Enfrento pressao por desmatamento e queimadas.',
    'Sou dividida entre varios paises sul-americanos.',
    'Meu maior rio compartilha meu nome em muitas linguas.',
    'Sou chamada por alguns de pulmão do mundo, embora a expressao seja debatida.',
    'Minha fauna inclui oncas, araras e botos.',
    'No Brasil, ocupo grande parte da regiao Norte.',
    'Tenho importancia climatica planetaria.',
    'Sou uma floresta tropical.',
    'Meu nome comeca com A.',
    'Tambem nomeio um estado brasileiro.',
    'Meu nome termina com nia.',
    'Sou a maior floresta tropical do planeta.',
    'Meu nome identifica uma regiao natural sul-americana gigantesca.',
  ],
  10: [
    'Sou um lugar de silencio relativo e concentracao.',
    'Minha funcao principal e guardar conhecimento organizado.',
    'Posso existir em escolas, bairros, universidades e meios digitais.',
    'Sou frequentada para estudo, pesquisa e leitura.',
    'Costumo ter regras sobre volume de voz.',
    'Em mim, obras ficam catalogadas por sistemas de classificacao.',
    'Emprestimos costumam ter prazo de devolucao.',
    'Ha profissionais especializados em curadoria de acervo.',
    'Posso ter setores infantil, tecnico e de referencia.',
    'Muitas pessoas me visitam em epoca de provas.',
    'Prateleiras e estantes sao elementos tipicos do meu espaco.',
    'Tambem posso oferecer acesso a rede mundial e bases academicas.',
    'Cartoes de usuario ajudam no controle de retirada.',
    'Autores de varias epocas convivem no meu acervo.',
    'Sou associada a livros, periodicos e manuscritos.',
    'Meu nome comeca com B.',
    'Sou um estabelecimento cultural comum.',
    'Sem mim, pesquisar fica muito mais dificil.',
    'Meu nome termina com teca.',
    'Sou o lugar classico para emprestimo de livros.',
  ],
  11: [
    'Sou um palco esportivo de enorme capacidade.',
    'Estou ligado a paixao coletiva e grandes classicos.',
    'Minha localizacao fica em uma cidade famosa por praias e morros.',
    'Ja recebi finais e eventos historicos do futebol.',
    'Minha atmosfera e conhecida por cantos de torcida.',
    'Passei por reformas para torneios internacionais recentes.',
    'Meu apelido remete a grandiosidade.',
    'Sou administrado como complexo multiuso em diferentes periodos.',
    'Fico na zona norte da minha cidade.',
    'Partidas da selecao brasileira ja aconteceram em mim.',
    'Recebi uma final de Copa do Mundo no seculo XX.',
    'Tambem sediou final de mundial de selecoes no seculo XXI.',
    'Meu bairro tem o mesmo nome que eu.',
    'Estou no Rio de Janeiro.',
    'Sou um estadio brasileiro muito famoso.',
    'Meu nome oficial homenageia um jornalista.',
    'O nome oficial inclui Mario Filho.',
    'Meu apelido comeca com Mara.',
    'Meu apelido termina com cana.',
    'Sou o estadio carioca mais famoso do pais.',
  ],
  12: [
    'Este ano marcou transformacoes simbolicas na corrida espacial.',
    'Foi uma epoca de mudancas culturais fortes no mundo.',
    'Aconteceu um grande festival de musica nos EUA.',
    'Uma franquia de ficcao cientifica estreou no cinema no fim do ano.',
    'Protestos e movimentos sociais cresceram em varios paises.',
    'A Guerra Fria influenciava quase toda decisao geopolitica.',
    'No Brasil, o periodo era de ditadura militar.',
    'Um ato institucional muito duro havia sido decretado pouco antes.',
    'Tecnologia de transmissao levou eventos para audiencias massivas.',
    'A disputa entre duas superpotencias estava no auge.',
    'Um modulo pousou em solo fora da Terra.',
    'Uma frase sobre um pequeno passo virou simbolo historico.',
    'Milhoes assistiram a chegada pela TV.',
    'A missao era da NASA.',
    'A nave envolvida foi a Apollo 11.',
    'Neil Armstrong participou desse feito.',
    'Foi o ano da primeira ida humana a Lua.',
    'Fica no fim da decada de 60.',
    'Vem imediatamente antes de 1970.',
    'E o ultimo ano da decada de 60.',
  ],
  13: [
    'Este ano alterou mapas politicos na Europa.',
    'Mudancas democraticas aceleraram no leste europeu.',
    'Foi um periodo de fim de blocos ideologicos rigidos.',
    'Imagens de multidoes derrubando barreiras ficaram famosas.',
    'No Brasil, aconteceu a primeira eleicao presidencial direta apos regime militar.',
    'A cultura pop viveu transicoes importantes no final da decada.',
    'A Uniao Sovietica ainda existia, mas enfraquecida.',
    'Discursos por liberdade ganharam forca em varios paises.',
    'Reformas economicas e politicas se intensificaram.',
    'A Guerra Fria se aproximava do encerramento.',
    'Em Pequim, manifestacoes estudantis terminaram com repressao.',
    'Na Alemanha, uma divisao fisica perdeu sentido.',
    'A queda de um muro simbolizou nova era europeia.',
    'Esse evento ocorreu em Berlim.',
    'No Brasil, Fernando Collor foi eleito.',
    'Fica no fim dos anos 80.',
    'E o ultimo ano antes de 1990.',
    'Termina com 89.',
    'Comeca com 19.',
    'E o ultimo ano da decada de 80.',
  ],
  14: [
    'Este ano comecou com grande tensao internacional.',
    'A tecnologia digital ja influenciava fortemente a vida urbana.',
    'Foi um periodo de mudancas em seguranca global.',
    'Mercados financeiros sentiram forte instabilidade no segundo semestre.',
    'Debates sobre vigilancia e fronteiras cresceram muito.',
    'No Brasil, energia eletrica virou tema cotidiano por causa de racionamento.',
    'No esporte, um brasileiro virou penta campeao mundial de Formula 1 na virada do ano.',
    'Na musica, o inicio dos anos 2000 consolidou novas tendencias pop.',
    'A rede mundial comercial seguia em expansao acelerada.',
    'Ataques coordenados chocaram os Estados Unidos.',
    'As imagens envolveram avioes e arranha-ceus.',
    'O Pentagono tambem foi atingido.',
    'A data desses ataques foi 11 de setembro.',
    'A chamada guerra ao terror ganhou impulso depois disso.',
    'Foi o primeiro ano do seculo XXI.',
    'Tambem foi o primeiro ano do terceiro milenio.',
    'Vem logo depois de 2000.',
    'Fica antes de 2002.',
    'Termina com 01.',
    'E o primeiro ano dos anos 2000.',
  ],
  15: [
    'Este ano e central para a historia politica do Brasil.',
    'Aconteceu no inicio do seculo XIX.',
    'Foi periodo de ruptura com uma metropole europeia.',
    'Movimentos locais ja defendiam autonomia havia algum tempo.',
    'A corte portuguesa havia se transferido para a America anos antes.',
    'Conflitos de interesse entre colonia e reino aumentaram.',
    'Um principe regente teve papel decisivo.',
    'Uma declaracao celebrou separacao politica.',
    'O episodio ficou associado a uma margem de rio paulista.',
    'A frase atribuida ao momento ficou muito conhecida nas escolas.',
    'Depois desse marco, iniciou-se organizacao do novo imperio.',
    'A data celebrada no calendario nacional e em setembro.',
    'O dia e sete de setembro.',
    'A independencia brasileira foi proclamada.',
    'O protagonista foi Dom Pedro I.',
    'Fica na decada de 1820.',
    'O ano termina com 22.',
    'Comeca com 18.',
    'Vem apos 1821.',
    'E o ano da independencia do Brasil.',
  ],
  16: [
    'Sou pequena, mas mudo direcoes em viagens.',
    'Funciono melhor quando posso me alinhar com um campo natural.',
    'Fui essencial para navegadores por seculos.',
    'Tenho relacao historica com exploracoes maritimas.',
    'Posso aparecer em versoes analogicas e digitais.',
    'Minha parte movel aponta para uma referencia fixa do planeta.',
    'Ajudo em trilhas, mapas e orientacao terrestre.',
    'Sou comum em kits de sobrevivencia.',
    'Posso ser integrada a relogios e celulares.',
    'Sem mim, orientar-se sem pontos visuais fica dificil.',
    'Meu funcionamento tradicional usa agulha magnetizada.',
    'Cardeais como norte e sul sao fundamentais para mim.',
    'No painel de carros, ha versoes eletronicas inspiradas em mim.',
    'Sou muito usada em atividades de escotismo.',
    'Meu corpo pode ser circular com rosa dos ventos.',
    'Meu nome comeca com B.',
    'Tenho dois ss no meio.',
    'Sou instrumento de orientacao.',
    'Meu nome termina com ola.',
    'Sou o instrumento classico que aponta o norte magnetico.',
  ],
  17: [
    'Produzo som por vibracao de cordas.',
    'Sou popular em rodas informais e palcos.',
    'Posso acompanhar voz em varios estilos.',
    'Existem modelos acusticos e eletricos aparentados comigo.',
    'Tenho corpo oco em uma versao muito comum.',
    'Mao esquerda e direita costumam ter funcoes diferentes ao tocar.',
    'Uso trastes para definir notas em grande parte dos modelos.',
    'Aprender acordes basicos e um passo inicial para iniciantes.',
    'Estou presente em samba, rock, pop, sertanejo e bossa.',
    'Posso ser tocado com dedos ou palheta.',
    'Minha afinacao padrao de seis cordas e bastante conhecida.',
    'No Brasil, sou presenca frequente em praias e encontros.',
    'Tenho parentes proximos como cavaquinho e viola.',
    'Meu braco se conecta a um corpo em formato caracteristico.',
    'Fabricantes usam madeiras variadas para timbre diferente.',
    'Meu nome comeca com V.',
    'Sou muito ensinado em aulas de musica.',
    'Nao sou um piano nem um violino.',
    'Tenho seis cordas na versao mais comum.',
    'Sou o instrumento de seis cordas mais comum nas rodas de musica.',
  ],
  18: [
    'Sou um animal marinho sem esqueleto interno rigido.',
    'Tenho inteligencia acima da media entre invertebrados.',
    'Consigo resolver problemas simples e abrir recipientes.',
    'Meu corpo e extremamente flexivel.',
    'Posso mudar de cor para camuflagem.',
    'Expulso tinta para confundir predadores.',
    'Vivo em oceanos de varias temperaturas.',
    'Tenho olhos muito desenvolvidos.',
    'Meu deslocamento pode ocorrer por jato de agua.',
    'Nao tenho concha externa como alguns parentes.',
    'Meus membros possuem ventosas.',
    'Cada membro consegue manipular objetos com precisao.',
    'Sou estudado em neurociencia por meu sistema nervoso complexo.',
    'Em culinarias costeiras, apareco em diferentes pratos.',
    'Meu nome em portugues e curto e termina com o.',
    'Tenho oito bracos.',
    'Pertenco ao grupo dos cefalopodes.',
    'Nao sou lula, embora seja parente.',
    'Meu nome comeca com P.',
    'Sou o cefalopode famoso por oito bracos com ventosas.',
  ],
  19: [
    'Nao sou objeto fisico, mas posso pesar muito.',
    'Apareco com forca quando existe distancia.',
    'Tenho relacao com memoria afetiva.',
    'Posso nascer de pessoas, lugares, fases ou cheiros.',
    'Sou tema frequente de musica e poesia.',
    'Nem sempre estou ligada a tristeza pura.',
    'Tambem posso trazer conforto e identidade.',
    'Sou dificil de traduzir literalmente para muitos idiomas.',
    'No Brasil, sou entendida de imediato em conversas.',
    'Estou presente quando algo importante fica para tras.',
    'Posso surgir em quem migra de cidade ou pais.',
    'Muitas cartas e cancoes antigas falam de mim.',
    'Sou um sentimento complexo.',
    'Misturo ausencia e carinho na mesma experiencia.',
    'Costumo crescer em datas comemorativas.',
    'Meu nome comeca com S.',
    'Tenho ditongo nasal na ultima silaba.',
    'Sou palavra muito associada ao portugues.',
    'Meu nome termina com dade.',
    'Sou o sentimento de falta carregado de afeto.',
  ],
  20: [
    'Conecto pessoas e informacoes em escala global.',
    'Nao sou um unico aparelho, mas uma rede gigantesca.',
    'Meu crescimento acelerou no fim do seculo XX.',
    'Permito comunicacao quase instantanea entre continentes.',
    'Sou base para emails, videos, mapas e mensagens.',
    'Tambem viabilizo compras, aulas e trabalho remoto.',
    'Tenho riscos ligados a privacidade e desinformacao.',
    'Meu funcionamento envolve protocolos de dados.',
    'Servidores, roteadores e cabos fazem parte da minha estrutura.',
    'Posso chegar por fibra, radio, satelite ou rede movel.',
    'Navegadores sao portas comuns para me acessar.',
    'Buscadores ajudam usuarios a encontrar conteudo dentro de mim.',
    'Redes sociais dependem fortemente da minha existencia.',
    'Sem mim, muitos servicos digitais param.',
    'No cotidiano, as pessoas dizem que estao sem sinal quando nao me alcancam.',
    'Meu nome comeca com I.',
    'A web e apenas uma parte de mim.',
    'Nao sou sinonimo exato de Wi-Fi.',
    'Tenho alcance mundial.',
    'Sou a rede digital global que conecta o mundo.',
  ],
}

export const TIPS = Object.entries(CARD_TIPS).flatMap(([cardId, tips]) =>
  tips.map((text, index) => ({
    id: (Number(cardId) - 1) * 20 + index + 1,
    cardId: Number(cardId),
    text,
    number: index + 1,
  })),
)