export const TIPS = [
  { id: 1, cardId: 1, text: 'É um ator.' },
  { id: 2, cardId: 1, text: 'É conhecido pela voz profunda e distinta.' },
  { id: 3, cardId: 1, text: 'Já ganhou um Oscar de atuação.' },
  { id: 4, cardId: 1, text: 'Costuma interpretar personagens sábios ou mentores.' },
  { id: 5, cardId: 1, text: 'Atuou em um filme ambientado em uma prisão.' },
  { id: 6, cardId: 1, text: 'É frequentemente requisitado como narrador.' },
  { id: 7, cardId: 1, text: 'Participou de um thriller policial sobre sete crimes.' },
  { id: 8, cardId: 1, text: 'Recebeu múltiplas indicações ao Oscar.' },
  { id: 9, cardId: 1, text: 'Já interpretou um presidente em um filme.' },
  { id: 10, cardId: 1, text: 'Trabalhou com o diretor Clint Eastwood.' },
  { id: 11, cardId: 1, text: 'Estrelou em filmes aclamados pela crítica.' },
  { id: 12, cardId: 1, text: 'Tem uma presença calma e autoritária em cena.' },
  { id: 13, cardId: 1, text: 'Começou a carreira na televisão e no teatro.' },
  { id: 14, cardId: 1, text: 'Ganhou reconhecimento internacional por papéis dramáticos.' },
  { id: 15, cardId: 1, text: 'Já interpretou um detetive experiente.' },
  { id: 16, cardId: 1, text: 'Também participou de filmes sobre catástrofes.' },
  { id: 17, cardId: 1, text: 'Tem uma filmografia longa e variada.' },
  { id: 18, cardId: 1, text: 'É frequentemente escalada para papéis de liderança moral.' },
  { id: 19, cardId: 1, text: 'Já recebeu prêmios de carreira e homenagens.' },
  { id: 20, cardId: 1, text: 'É reconhecida pela capacidade de narrar histórias poderosas.' },

  { id: 21, cardId: 2, text: 'É um detetive fictício criado por Sir Arthur Conan Doyle.' },
  { id: 22, cardId: 2, text: 'Trabalha frequentemente com o Dr. John Watson.' },
  { id: 23, cardId: 2, text: 'Vive na rua Baker Street, em Londres.' },
  { id: 24, cardId: 2, text: 'É famoso pelo uso da lógica e da observação.' },
  { id: 25, cardId: 2, text: 'Toca violino em momentos de reflexão.' },
  { id: 26, cardId: 2, text: 'Seu arqui-inimigo é o professor Moriarty.' },
  { id: 27, cardId: 2, text: 'É conhecido por usar disfarces durante investigações.' },
  { id: 28, cardId: 2, text: 'É frequentemente retratado fumando cachimbo.' },
  { id: 29, cardId: 2, text: 'Tem uma personalidade reservada e analítica.' },
  { id: 30, cardId: 2, text: 'Resolve crimes aparentemente insolúveis.' },
  { id: 31, cardId: 2, text: 'Utiliza raciocínio dedutivo para tirar conclusões.' },
  { id: 32, cardId: 2, text: 'Aparece em contos e romances publicados entre os séculos XIX e XX.' },
  { id: 33, cardId: 2, text: 'Seu ajudante e narrador das histórias é o Dr. Watson.' },
  { id: 34, cardId: 2, text: 'É frequentemente associado a lupas e microscópios.' },
  { id: 35, cardId: 2, text: 'Seus casos dependem de pistas quase imperceptíveis.' },
  { id: 36, cardId: 2, text: 'Há muitas adaptações para cinema e televisão.' },
  { id: 37, cardId: 2, text: 'É um ícone da ficção criminal clássica.' },
  { id: 38, cardId: 2, text: 'O endereço 221B Baker Street é ligado ao personagem.' },
  { id: 39, cardId: 2, text: 'Seus métodos inspiraram práticas forenses modernas.' },
  { id: 40, cardId: 2, text: 'Frequentemente é representado com um chapéu tipo deerstalker.' },

  { id: 41, cardId: 3, text: 'Forrest Gump estreou nos cinemas nesse ano.' },
  { id: 42, cardId: 3, text: 'Pulp Fiction foi lançado e marcou o cinema independente.' },
  { id: 43, cardId: 3, text: 'The Shawshank Redemption estreou e ganhou público cult.' },
  { id: 44, cardId: 3, text: 'O filme O Rei Leão foi lançado pela Disney.' },
  { id: 45, cardId: 3, text: 'Nelson Mandela foi empossado como presidente da África do Sul.' },
  { id: 46, cardId: 3, text: 'A Copa do Mundo da FIFA foi sediada pelos Estados Unidos.' },
  { id: 47, cardId: 3, text: 'Kurt Cobain, vocalista do Nirvana, morreu neste ano.' },
  { id: 48, cardId: 3, text: 'A Amazon foi fundada por Jeff Bezos.' },
  { id: 49, cardId: 3, text: 'O ano marcou avanços significativos na internet comercial.' },
  { id: 50, cardId: 3, text: 'Vários filmes que se tornaram clássicos estrearam nesse ano.' },
  { id: 51, cardId: 3, text: 'A série Friends estreou na televisão.' },
  { id: 52, cardId: 3, text: 'Netscape ainda era um navegador dominante na época.' },
  { id: 53, cardId: 3, text: 'Houve lançamentos musicais e álbuns influentes naquele ano.' },
  { id: 54, cardId: 3, text: 'O filme Speed foi lançado.' },
  { id: 55, cardId: 3, text: 'A perseguição de carro envolvendo O.J. Simpson aconteceu neste ano.' },
  { id: 56, cardId: 3, text: 'As Olimpíadas de Inverno ocorreram em Lillehammer, Noruega.' },
  { id: 57, cardId: 3, text: 'Viu o crescimento rápido de empresas de tecnologia.' },
  { id: 58, cardId: 3, text: 'O comércio eletrônico começou a ganhar força.' },
  { id: 59, cardId: 3, text: 'Muitos lançamentos culturais continuam populares hoje.' },
  { id: 60, cardId: 3, text: 'O ano foi marcado por eventos políticos e culturais globais.' },

  { id: 61, cardId: 4, text: 'É usado para medir o tempo.' },
  { id: 62, cardId: 4, text: 'Pode ser mecânico ou digital.' },
  { id: 63, cardId: 4, text: 'Modelos analógicos geralmente têm ponteiros para horas e minutos.' },
  { id: 64, cardId: 4, text: 'Alguns exibem a hora em telas LED ou LCD.' },
  { id: 65, cardId: 4, text: 'Os de pulso são usados preso ao pulso.' },
  { id: 66, cardId: 4, text: 'Os de parede são comuns em casas e escritórios.' },
  { id: 67, cardId: 4, text: 'Alguns têm função de cronógrafo (cronômetro).' },
  { id: 68, cardId: 4, text: 'Também funcionam como acessórios de moda.' },
  { id: 69, cardId: 4, text: 'Existem modelos resistentes à água.' },
  { id: 70, cardId: 4, text: 'Os atômicos são extremamente precisos.' },
  { id: 71, cardId: 4, text: 'Muitos têm alarme integrado.' },
  { id: 72, cardId: 4, text: 'Os mecânicos usam engrenagens e mola principal.' },
  { id: 73, cardId: 4, text: 'Os de bolso foram populares no passado.' },
  { id: 74, cardId: 4, text: 'Marcas famosas produzem de luxo tradicionais.' },
  { id: 75, cardId: 4, text: 'Podem ter pulseiras de couro, tecido ou metal.' },
  { id: 76, cardId: 4, text: 'Os inteligentes conectam-se a celulares e apps.' },
  { id: 77, cardId: 4, text: 'Alguns modelos mostram calendário e fases da lua.' },
  { id: 78, cardId: 4, text: 'São usados tanto para função prática quanto estética.' },
  { id: 79, cardId: 4, text: 'Podem servir em experimentos científicos para medir intervalos.' },
  { id: 80, cardId: 4, text: 'É um símbolo comum de pontualidade.' },

  { id: 81, cardId: 5, text: 'É a capital da França.' },
  { id: 82, cardId: 5, text: 'Tem a Torre Eiffel como um ponto turístico icônico.' },
  { id: 83, cardId: 5, text: 'O rio Sena corta a cidade.' },
  { id: 84, cardId: 5, text: 'O Museu do Louvre abriga a Mona Lisa.' },
  { id: 85, cardId: 5, text: 'É famosa pela gastronomia e seus cafés.' },
  { id: 86, cardId: 5, text: 'Aqui se encontra a Catedral de Notre-Dame.' },
  { id: 87, cardId: 5, text: 'A avenida Champs-Élysées é conhecida por lojas e eventos.' },
  { id: 88, cardId: 5, text: 'É dividida em arrondissements numerados.' },
  { id: 89, cardId: 5, text: 'É um importante centro de arte e moda.' },
  { id: 90, cardId: 5, text: 'Montmartre é um bairro famoso por artistas e vistas.' },
  { id: 91, cardId: 5, text: 'O metrô é extenso e antigo.' },
  { id: 92, cardId: 5, text: 'A cidade atrai milhões de turistas anualmente.' },
  { id: 93, cardId: 5, text: 'O Palácio de Versalhes fica nos arredores.' },
  { id: 94, cardId: 5, text: 'Sediou eventos históricos e revoluções.' },
  { id: 95, cardId: 5, text: 'É um destino popular para viagens românticas.' },
  { id: 96, cardId: 5, text: 'A língua oficial da cidade é o francês.' },
  { id: 97, cardId: 5, text: 'Tem muitos parques e jardins públicos.' },
  { id: 98, cardId: 5, text: 'Bairros como Le Marais e Rue de Rivoli são conhecidos.' },
  { id: 99, cardId: 5, text: 'Abriga renomadas escolas de arte e design.' },
  { id: 100, cardId: 5, text: 'O Arco do Triunfo homenageia soldados e líderes franceses.' },
];